### ISSUE TITLE
Discord link is bork

### ISSUE THREAD

**Issue by nichlas0010** [OuterHaven13/OuterHaven13#24]
Whoever added this didn't make it a permanent link. Rip.

Here's the line in question:
https://github.com/OuterHaven13/OuterHaven13/blob/35b890fb02f1fe5095c77ba0ca952c15360390e4/config/motd.txt#L7

**Comment by Partheo** [comment]
Funny guy

**Comment by nichlas0010** [comment]
apparently this is the wrong git. Whod've thonked
